version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql-container
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: mysql-server
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    command: --wait_timeout=28800 --interactive_timeout=28800

  redis:
    image: redis:7.2
    container_name: my-redis-container
    restart: always
    ports:
      - "6379:6379" # 기본 포트
