version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql-container
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mysql_server
      MYSQL_ROOT_PASSWORD: rpdla123
      MYSQL_USER: diajd1
      MYSQL_PASSWORD: rpdla123
    command: --wait_timeout=28800 --interactive_timeout=28800

  redis:
    image: redis:7.2
    container_name: my-redis-container
    restart: always
    ports:
      - "6379:6379" # 기본 포트
