"""image_model_create2

Revision ID: 8a17390c2642
Revises: c7d3e3e072d9
Create Date: 2025-03-31 16:34:15.728197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a17390c2642'
down_revision: Union[str, None] = 'c7d3e3e072d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_ibfk_1', 'image', type_='foreignkey')
    op.create_foreign_key(None, 'image', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.create_foreign_key('image_ibfk_1', 'image', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
